apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.clusterSecretStore.name }}
  labels:
  {{- include "central-secret-operator.labels" . | nindent 4 }}
spec:
  provider:
    {{- if .Values.googleCloud.enabled }}
    gcpsm:
      auth:
        workloadIdentity:
          serviceAccountRef:
            name: {{ .Values.serviceAccount.name }}
            namespace: {{ .Values.serviceAccount.namespace }}
      projectID: {{ .Values.clusterSecretStore.targetProjectId }}
    {{- end }}
    {{- if .Values.aws.enabled }}
    aws:
      service: SecretsManager
      region: {{ .Values.aws.setupIAM.region }}
      {{- if eq .Values.aws.authMethod "irsa" }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.serviceAccount.name }}
            namespace: {{ .Values.serviceAccount.namespace }}
      {{- end }}
    {{- end }}
