{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.serviceAccount.namespace }}
  labels:
    {{- include "central-secret-operator.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.googleCloud.enabled }}
    iam.gke.io/gcp-service-account: {{ printf "%s@%s.iam.gserviceaccount.com" .Values.googleCloud.setupIAM.serviceAccountName .Values.googleCloud.setupIAM.projectId | quote }}
    {{- end }}
    {{- if .Values.aws.enabled }}
    eks.amazonaws.com/role-arn: {{ .Values.aws.setupIAM.iamRoleArn | quote }}
    {{- end }}
{{- end -}}