{{- range .Values.secrets }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  refreshInterval: {{ .refreshInterval | default "1h" }}
  secretStoreRef:
    kind: {{ .storeKind | default "ClusterSecretStore" }}
    name: {{ .storeName | default "cluster-secret-store" }}
  target:
    name: {{ .targetName }}
    template:
      type: {{ .targetType }}
  data:
    {{- range .data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRef.key }}
        {{- if .remoteRef.property }}
        property: {{ .remoteRef.property }}
        {{- end }}
        {{- if .remoteRef.version }}
        version: {{ .remoteRef.version }}
        {{- end }}
        {{- if .remoteRef.decodingStrategy }}
        decodingStrategy: {{ .remoteRef.decodingStrategy }}
        {{- end }}
    {{- end }}

{{- end }}
