serviceAccount:
  name: external-secrets

image:
  repository: 490083271972.dkr.ecr.af-south-1.amazonaws.com/aibplus-images/external-secrets

webhook:
  image:
    repository: 490083271972.dkr.ecr.af-south-1.amazonaws.com/aibplus-images/external-secrets

certController:
  image:
    repository: 490083271972.dkr.ecr.af-south-1.amazonaws.com/aibplus-images/external-secrets

