image:
  repository: 490083271972.dkr.ecr.af-south-1.amazonaws.com/aibplus-images/aib-plus-rai  # Change by AIB+ Market
  tag: v1.3

name: rai
namespace: aib-system

replicaCount: 1

service:
  type: ClusterIP
  port: 80
  targetPort: 8080
  protocol: TCP

resources:
  requests:
    cpu: 500m
    memory: 2Gi
  limits:
    cpu: 1
    memory: 3Gi

sa_annotations:
  eks.amazonaws.com/role-arn: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx