{{- range .Values.clusterRoleBindings }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .name }}
subjects:
{{ toYaml .subjects | indent 2 }}
roleRef:
{{ toYaml .roleRef | indent 2 }}
{{- end }}
