{{- range $name, $policy := .Values.policies }}
{{- if and $policy.enabled (eq (default "validate" $policy.type) "generate") }}
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: {{ $name }}
  labels:
    {{- include "kyverno-policies.labels" $ | nindent 4 }}
    {{- with $policy.category }}
    app.kubernetes.io/component: {{ . | lower | replace " " "-" }}
    {{- end }}
  annotations:
    policies.kyverno.io/title: {{ $policy.title | quote }}
    {{- with $policy.category }}
    policies.kyverno.io/category: {{ . | quote }}
    {{- end }}
    {{- with $policy.severity }}
    policies.kyverno.io/severity: {{ . | quote }}
    {{- end }}
    {{- with $policy.description }}
    policies.kyverno.io/description: {{ . | quote }}
    {{- end }}
    {{- with $policy.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  background: {{ hasKey $policy "background" | ternary $policy.background true }}
  rules:
  {{- range $policy.rules }}
    - name: {{ .name }}
      {{- include "kyverno-policies.matchExclude" . | nindent 6 }}
      {{- with .preconditions }}
      preconditions:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      generate:
        synchronize: {{ .generate.synchronize | default false }}
        apiVersion: {{ .generate.apiVersion }}
        kind: {{ .generate.kind }}
        name: {{ .generate.name | quote }}
        namespace: {{ .generate.namespace | quote }}
        data:
          {{- toYaml .generate.data | nindent 10 }}
  {{- end }}
{{- end }}
{{- end }}
