{{- if .Values.jobRunner.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.jobRunner.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.jobRunner.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ include "mlrun-ce.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: job-runner
{{- end }}
